[project]
name = "ecomm-chuhai"
version = "0.1.0"
description = "一键出海"
readme = "README.md"
requires-python = ">=3.10.1"
dependencies = [
    "crawl4ai>=0.6.3",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=8.36.0",
]
